// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Codemirror: typeof import('./src/components/Codemirror.vue')['default']
    'ICarbon:close': typeof import('~icons/carbon/close')['default']
    'ICarbon:code': typeof import('~icons/carbon/code')['default']
    'ICarbon:connect': typeof import('~icons/carbon/connect')['default']
    'ICarbon:copy': typeof import('~icons/carbon/copy')['default']
    'ICarbon:dataBase': typeof import('~icons/carbon/data-base')['default']
    'ICarbon:dotMark': typeof import('~icons/carbon/dot-mark')['default']
    'ICarbon:newTab': typeof import('~icons/carbon/new-tab')['default']
    'ICarbon:queryQueue': typeof import('~icons/carbon/query-queue')['default']
    'ICarbon:time': typeof import('~icons/carbon/time')['default']
    'ICarbon:upload': typeof import('~icons/carbon/upload')['default']
    ICarbonAdd: typeof import('~icons/carbon/add')['default']
    ICarbonCopy: typeof import('~icons/carbon/copy')['default']
    ICarbonCsv: typeof import('~icons/carbon/csv')['default']
    ICarbonDownload: typeof import('~icons/carbon/download')['default']
    ICarbonGithub: typeof import('~icons/carbon/github')['default']
    ICarbonLanguage: typeof import('~icons/carbon/language')['default']
    ICarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    ICarbonMoon: typeof import('~icons/carbon/moon')['default']
    ICarbonPlayFilledAlt: typeof import('~icons/carbon/play-filled-alt')['default']
    ICarbonSave: typeof import('~icons/carbon/save')['default']
    ICarbonSettings: typeof import('~icons/carbon/settings')['default']
    ICarbonSql: typeof import('~icons/carbon/sql')['default']
    ICarbonSql32: typeof import('~icons/carbon/sql32')['default']
    ICarbonSun: typeof import('~icons/carbon/sun')['default']
  }
}

export { }
